import { NextResponse } from 'next/server';
import { getInvoiceById, addInvoice, addInvoiceHistory } from '@/lib/db';
import { verifyAuth } from '@/lib/auth';

export async function POST(
  request: Request,
  props: { params: Promise<{ id: string }> }
) {
  try {
    if (!(await verifyAuth())) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const params = await props.params;
    const { id } = params;
    const sourceInvoice = await getInvoiceById(id);
    if (!sourceInvoice) {
      return NextResponse.json({ error: 'Source invoice not found' }, { status: 404 });
    }

    const dupNumber = `${sourceInvoice.invoiceNumber}-DUP-${Math.floor(10 + Math.random() * 90)}`;
    const dupItems = sourceInvoice.items.map((item: any) => ({
      serviceName: item.serviceName,
      description: item.description,
      quantity: item.quantity,
      price: item.price,
      tax: item.tax,
      total: item.total
    }));

    const result = await addInvoice({
      invoiceNumber: dupNumber,
      bookingId: sourceInvoice.bookingId,
      clientId: sourceInvoice.clientId,
      issueDate: new Date().toISOString().split('T')[0],
      dueDate: sourceInvoice.dueDate,
      discount: sourceInvoice.discount,
      tax: sourceInvoice.tax,
      paidAmount: 0, // Duplicate starts as unpaid
      notes: sourceInvoice.notes,
      status: 'Draft'
    }, dupItems);

    await addInvoiceHistory(sourceInvoice.id, 'Invoice Duplicated', `Created duplicate invoice ${dupNumber}`);
    await addInvoiceHistory(result.id, 'Invoice Generated by Duplication', `Cloned from ${sourceInvoice.invoiceNumber}`);

    return NextResponse.json({ success: true, invoice: result });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
